import type { PrismaClient } from "@/generated/prisma/client";
import { slugify } from "@/lib/slugify";

// Source: the user's other Lovable/Supabase-backed events site
// (plusparty-co-il.lovable.app). Snapshot pulled via the Lovable MCP
// query_database tool — see the "PlusParty sync" Routine for how this file
// gets regenerated on a schedule to pick up new/updated events.
export const PLUSPARTY_SOURCE = "plusparty";

interface PlusPartySourceEvent {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  region: "tzafon" | "merkaz" | "darom";
  kind: "party" | "show";
  event_date: string;
  location: string | null;
  image_url: string | null;
  external_link: string | null;
  price: string | null;
  featured: boolean;
  meta_title: string | null;
  meta_description: string | null;
}

const REGION_LABELS: Record<PlusPartySourceEvent["region"], string> = {
  tzafon: "צפון",
  merkaz: "מרכז",
  darom: "דרום",
};

const KIND_CATEGORY: Record<PlusPartySourceEvent["kind"], { name: string; slug: string; icon: string }> = {
  party: { name: "מסיבות", slug: "parties", icon: "party" },
  show: { name: "הופעות", slug: "shows", icon: "mic" },
};

function networkFromUrl(url: string | null): string | undefined {
  if (!url) return undefined;
  try {
    const host = new URL(url).hostname.replace(/^(www|app)\./, "");
    const label = host.split(".")[0];
    return label
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ");
  } catch {
    return undefined;
  }
}

// Paste the output of the sync query here to update the snapshot:
//   select id, slug, title, description, region, kind, event_date, location,
//          image_url, external_link, price, featured, meta_title, meta_description
//   from events where published = true order by event_date asc;
const SOURCE_EVENTS: PlusPartySourceEvent[] = [
  {"id":"1f2ecae1-3768-4c3b-a023-e9f84bd4a56f","slug":"rokdim-in-the-kibutz","title":"רוקדים בקיבוץ 35+","description":"הגיע הזמן למסיבה כמו שצריך!\nעם הקהל הנכון (כי מישהו צריך לדעת להעריך מוזיקה טובה ואלכוהול משובח).\nבאים לפתוח את הקיץ עם אלכוהול טוב, מוזיקה שתעיף אותנו, ואפס מחשבות על מחר.\nעל העמדה: DJ PELEG BAR שיעיף אותנו באוויר עם מיינסטרים איכותי.\nעל הבר: בר קוקטיילים קיציים ומרעננים.\nבירה קרירה וצוננת היישר מהחבית.\nוויסקי משובח ועוד ועוד ועוד ..\nמחירי קיבוץ כמובן.","region":"tzafon","kind":"party","event_date":"2026-07-04 19:00:00+00","location":"קיבוץ רמת השופט","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/4f2e0b74-71be-4c7b-9220-0520195e6aa5.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNGYyZTBiNzQtNzFiZS00YzdiLTkyMjAtMDUyMDE5NWU2YWE1LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM1NDI2NTYsImV4cCI6MjA5ODkwMjY1Nn0.ULA3I8f_e6VmZLdqndz8w_YcWNcuX9JKbog-Kt-a3ME","external_link":"https://app.partiq.co/party/EaSKPn?pr=75b002dd52","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"2e733b6e-e64b-427b-bdae-ba676fa12c74","slug":"Techno Park","title":"Techno Park ☼ Daytime Experience ","description":"הפקת צהריים באוויר הפתוח ברחבה בלתי נגמרת.\nבשילוב סוללת אמנים מהצהריים עד הלילה,\nניצא למסע חדש בנוף השדות של עמק יזרעאל!\nהטכנו פארק חוזר באפטר עם האמנים הגדולים ביותר במדינה:\nמאור בוזגלו | הודיה בלוטאק ועוד רבים וטובים.\nאז שווה לכם לרכוש במחיר המוזל שלנו.","region":"tzafon","kind":"party","event_date":"2026-07-11 14:00:00+00","location":"כחול וירוק, גן אירועים","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/850daef7-22f2-425c-a1ed-0d60f7afb307.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvODUwZGFlZjctMjJmMi00MjVjLWExZWQtMGQ2MGY3YWZiMzA3LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MTA0NTYsImV4cCI6MjA5ODk3MDQ1Nn0.3cBloUfpAjWhCBZS8QRknOi2lPU6MHKOgEGUM2OWhgQ","external_link":"https://www.eventer.co.il/event/techno_park/8MsYL","price":null,"featured":false,"meta_title":null,"meta_description":null},
  {"id":"d05f250e-45e3-46a2-8d6a-1cfb3c074b99","slug":"summer wine","title":"summer wine","description":"הקיץ כבר כאן, ואנחנו מצאנו את הדרך המושלמת להעביר את ערבי הקיץ החמים – עם כוס יין צוננת ביד, בריזה טובה ואווירה שלא תרצו שתיגמר.\nמחכים לכם בפסטיבל יין חגיגי במיוחד שמביא את היקבים הכי שווים, דוכני אוכל מטריפים, אקססוריז, מוזיקה מעולה ואנשים טובים.","region":"tzafon","kind":"party","event_date":"2026-07-16 18:00:00+00","location":"תל עדשים","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/2e696624-d256-434e-a1be-336361cb797d.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMmU2OTY2MjQtZDI1Ni00MzRlLWExYmUtMzM2MzYxY2I3OTdkLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM5NDU1NzcsImV4cCI6MjA5OTMwNTU3N30.BfUTsQCgK16n9EcEm_R4pHkE2t9DgjuMW1npD3I5aUQ","external_link":"https://www.eventer.co.il/event/winesetsummer/Y5vYL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"54089eb5-d1e8-4253-acf6-fd0d03818b95","slug":"rokdim-in-the-kibutz-copy","title":"רוקדים בקיבוץ 35+ ","description":"הגיע הזמן למסיבה כמו שצריך!\nעם הקהל הנכון (כי מישהו צריך לדעת להעריך מוזיקה טובה ואלכוהול משובח).\nבאים לפתוח את הקיץ עם אלכוהול טוב, מוזיקה שתעיף אותנו, ואפס מחשבות על מחר.\nעל העמדה: DJ PELEG BAR שיעיף אותנו באוויר עם מיינסטרים איכותי.","region":"tzafon","kind":"party","event_date":"2026-07-16 19:00:00+00","location":"קיבוץ רמת השופט","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/4f2e0b74-71be-4c7b-9220-0520195e6aa5.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNGYyZTBiNzQtNzFiZS00YzdiLTkyMjAtMDUyMDE5NWU2YWE1LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM1NDI2NTYsImV4cCI6MjA5ODkwMjY1Nn0.ULA3I8f_e6VmZLdqndz8w_YcWNcuX9JKbog-Kt-a3ME","external_link":"https://app.partiq.co/party/EaSKPn?pr=75b002dd52","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"06d092d1-9375-4aed-aa16-57026738e465","slug":"Kontra-party","title":"Kontra","description":"ברוכים הבאים למסע של צלילים, טבע ואנרגיה חופשית.\nמוזיקה שתיקח אתכם למסע, טבע פתוח ואווירה קסומה, אנשים יפים ואנרגיות טובות, חוויה שלא תשכחו.\nליין אפ שנחשף: Mimos, Static Movement.","region":"merkaz","kind":"party","event_date":"2026-07-16 20:00:00+00","location":"20 דקות צפונה מתל אביב","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/93e4e8d3-5058-4225-9468-7ce21616f3fe.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvOTNlNGU4ZDMtNTA1OC00MjI1LTk0NjgtN2NlMjE2MTZmM2ZlLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MTA1MDYsImV4cCI6MjA5ODk3MDUwNn0.xN-sbAXYA7GGPLjGYM3yNNkCF6Qymh2tbZtXcyOuq5Y","external_link":"https://eventbuzz.co.il/lp/event/kontra?s=24750","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"934f6548-1121-482a-90fc-c6886e7027e7","slug":"trance-party-music","title":"מסיבת טראנס משוגעת ויום הולדת לאלי","description":"הגיע הזמן לחגוג כמו שרק אנחנו יודעים! מסיבת טראנס במקום הכי יפה בארץ, עם אומנים מהשורה הראשונה, רחבה מטורפת, סאונד עוצמתי והמון אהבת חינם. חגיגת יום הולדת שתיחרט בזיכרון.","region":"tzafon","kind":"party","event_date":"2026-07-16 20:30:00+00","location":"לוקיישן פרטי ומהפנט","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/487610e4-7ad2-4388-8a57-49a9559e90ce.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNDg3NjEwZTQtN2FkMi00Mzg4LThhNTctNDlhOTU1OWU5MGNlLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM1NDQxNjMsImV4cCI6MjA5ODkwNDE2M30.3cza4sbI8X5REN9ZAd8g9vNNYFiOE0dm-TLQw49FPaI","external_link":"https://selector.org.il/e/j8_yUrKgnle","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"bb1dc826-2d1f-47c5-9872-5fca9841be66","slug":"Timeless Experience","title":"Timeless Experience","description":"זה לא עוד מסיבה. זה קונצרט אלקטרוני שייתן חוויה חד פעמית! יותר מ-30 שנות יצירה, אינספור במות ברחבי העולם, וקריירה אחת שהפכה את Skazi לאחד מהשמות הגדולים והמשפיעים בתולדות הטראנס הישראלי והעולמי.","region":"tzafon","kind":"party","event_date":"2026-07-17 19:00:00+00","location":"עמק יזראל","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/7dea292d-98d4-4892-917c-28fe8504be93.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvN2RlYTI5MmQtOThkNC00ODkyLTkxN2MtMjhmZTg1MDRiZTkzLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM4NjcxNDQsImV4cCI6MjA5OTIyNzE0NH0.n_vqqf-W2EzIAk1YyEstX9UKsL4WqY0XoJChGSpNVn0","external_link":"https://www.eventer.co.il/event/timeless_experience/blvYL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"e16f45c4-05b4-4566-ba6f-9598d2d59682","slug":"giora-zinger","title":"גיורא זינגר","description":"במופע הסטנדאפ שלו, גיורא זינגר מספר לכם על הבית הרוסי שלו וגם על הבית הישראלי של כולנו. בעזרת המון חוש הומור, חדות וכריזמה גיורא יזכיר לכם את הילדות.","region":"tzafon","kind":"show","event_date":"2026-07-17 19:00:00+00","location":"היכל התרבות מוזה, חוף הכרמל","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/e5cc67ed-3236-49c3-8beb-2bd400547b4c.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZTVjYzY3ZWQtMzIzNi00OWMzLThiZWItMmJkNDAwNTQ3YjRjLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MTAxNTAsImV4cCI6MjA5ODk3MDE1MH0.zQHgQPWxRQXpygaMlBJ4Qe_EYhTfJfyL3qtZWA-ouww","external_link":"https://castilia.co.il/he/Event/Order?eventId=5072","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"7376939a-ae3a-419d-ad49-0bb171839a68","slug":"WUNDERGORUND-PRS","title":"WUNDERGORUND PRS: SUMMER DAZE","description":"הקיץ כבר כאן, והשרב הגדול הוא כבר חלק מהשגרה. עם מערכת סאונד מושלמת, האמנים האיכותיים ביותר בארץ ובעולם, והקהל הנדיר של אנדרגראונד טים, אנחנו ממשיכים להביא את הווייב של עשרים שנות הפקת מסיבות טבע, אל תוך הלב של העיר.","region":"tzafon","kind":"party","event_date":"2026-07-23 20:00:00+00","location":"מועדן הוונדר בר ","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/e83a5112-10c3-4295-a9de-013ec6e55edc.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZTgzYTUxMTItMTBjMy00Mjk1LWE5ZGUtMDEzZWM2ZTU1ZWRjLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM1NDM0NjYsImV4cCI6MjA5ODkwMzQ2Nn0.A3RhkSxhIkoSsNJKuFzQ4uK74CkkodfoHerCX_2yxso","external_link":"https://eventbuzz.co.il/lp/event/summerdaze?s=24124","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"597b88bd-c982-448d-8aa9-6e276402d533","slug":"MAREE ROOFTOP ","title":"שישי בלבן ","description":"שישי בלבן | MAREE ROOFTOP. הקיץ ממשיך בגג הכי יפה בישראל. שישי בלבן חוזר ל־MAREE על גג מלון ורט לגון בנתניה, מול הים. LINEUP: ITAY GALO, HODAYA, DANICO, ZARCHI, MOGI, INGADOS, ZFANIA.","region":"merkaz","kind":"party","event_date":"2026-07-24 09:45:00+00","location":"נתניה","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/9253ce22-eb3f-4cdc-8651-d44246cd3063.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvOTI1M2NlMjItZWIzZi00Y2RjLTg2NTEtZDQ0MjQ2Y2QzMDYzLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQwMTMxMTIsImV4cCI6MjA5OTM3MzExMn0.JVLE8XvYfNoF6088eb0q5WBR07z99SOPQLE35PxrDaQ","external_link":"https://zygo.co.il/event/180774076445140652/ZF10i08p9","price":null,"featured":false,"meta_title":null,"meta_description":null},
  {"id":"9d279d97-46cc-4787-847f-0d6063e12316","slug":"Tu B'Av Festival","title":"פסטיבל ט\"ו באב בגושפנקא","description":"מרגישים את הניצוצות באוויר?? מחכה לנו לילה של אהבה. לא משנה אם אתם מגיעים כזוג, עם החברים הכי טובים, או אולי דווקא בתקווה להכיר מישהו חדש. לילה של מוזיקה, קיץ, אנשים יפים, 3 רחבות, דרינקים, דוכני אוכל ומתחם משחקים חדש.","region":"tzafon","kind":"party","event_date":"2026-07-24 19:30:00+00","location":"גושפנקא","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/f5d6036c-2310-4e64-b515-55d40c8d877b.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZjVkNjAzNmMtMjMxMC00ZTY0LWI1MTUtNTVkNDBjOGQ4NzdiLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQyMDgzODAsImV4cCI6MjA5OTU2ODM4MH0.2t_tZjIo5YAWIBC9da02yRfPQZbOdyHhlSDALiE3If8","external_link":"https://chillz.com/en/uy9r-3-30-24.7-uy9r?ref=GFXOX","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"ba5dd438-18ca-4177-bbaf-38ddfcb20e0b","slug":"Urban-music","title":"Urban Music","description":"Line Up: Pettra, Animato, All In One, Cosmic Freaks (Cosmic Flow & Freak Show), Shibass, Xstava, Slava, Jeremy Tsunami. ציליה מטורפת, הגברה עוצמתית, טפטפות. גילאי 30+.","region":"merkaz","kind":"party","event_date":"2026-07-25 11:00:00+00","location":"ראשון לציון ","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/e8be12a1-9914-42f7-8cc0-46f4567f9461.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZThiZTEyYTEtOTkxNC00MmY3LThjYzAtNDZmNDU2N2Y5NDYxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM5MzQ1ODEsImV4cCI6MjA5OTI5NDU4MX0.PAazXyXPbL_tsPbJAchzx6ncAGngPX9SCDDG9t7ll_A","external_link":"https://zygo.co.il/event/710755135495404325/ZF10i08p9","price":null,"featured":false,"meta_title":null,"meta_description":null},
  {"id":"e3365382-3547-4e01-ad1e-0bb39a0c015e","slug":"daniel-cohen-ako","title":"דניאל כהן בעכו","description":"דניאל כהן, קומיקאי, נשוי לראש הכת ואבא גאה לסגן ראש הכת ולממלא מקום משנה לסגן ראש הכת. הסטנדאפיסט המוביל ותופעת הרשת, כוכב ״ערב עם שי שטרן״, ״מה שתגידו״ ועוד במופע סטנדאפ משובח מושחז ובוגר שלא כדאי להחמיץ!","region":"tzafon","kind":"show","event_date":"2026-07-25 18:30:00+00","location":"היכל התרבות עכו","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/64e826b4-4bf1-47f7-83b6-df72619b58d4.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNjRlODI2YjQtNGJmMS00N2Y3LTgzYjYtZGY3MjYxOWI1OGQ0LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MDk4ODMsImV4cCI6MjA5ODk2OTg4M30.CWABs5M7pB3kOomEJiEUYxjbtD42CnP-NEiouKrjNsA","external_link":"https://castilia.co.il/he/Event/Order?eventId=5425","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"9db32a51-ac1c-47df-9f35-d88ad3d5fc89","slug":"DECISION FESTIVAL","title":"DECISION FESTIVAL","description":"איפה שהמוזיקה, האנרגיה והאנשים הופכים לאחד. ב-DECISION כל צליל, מלודיה ובאס יוצרים מסע עוצמתי של חופש, חיבור ורגעים בלתי נשכחים. לילה אחד. אנרגיה אינסופית. חוויה שלא תשכחו.","region":"merkaz","kind":"party","event_date":"2026-07-30 20:30:00+00","location":"מתחם גגרין תל אביב","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/bf71702d-7598-44aa-b35f-7ff4fc3e6bba.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvYmY3MTcwMmQtNzU5OC00NGFhLWIzNWYtN2ZmNGZjM2U2YmJhLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM5NzM4MzYsImV4cCI6MjA5OTMzMzgzNn0.Cc9tpOZqUiAX-AU2S6cw7MGCiH4eCWl3AHi6i5iIbUk","external_link":"https://zygo.co.il/event/110739135723565686/ZF10i08p9","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"f0ba1f5e-1c66-40b0-bdd6-aa0bfa16ffaa","slug":"The Northern Gathering","title":"טרקטור בטבע ואלקטרו פארק יוצאים לדרך!","description":"אנחנו בשיאו של הקיץ הגדול, וזה בדיוק הזמן לצאת אל אוויר הלילה הקריר. טרקטור בטבע ואלקטרו פארק, מזמינים אתכם לחוויית לילה יוצאת דופן בלב עמק יזרעאל בין השדות. פסטיבל טראנס לילי אמיתי.","region":"tzafon","kind":"party","event_date":"2026-07-31 19:00:00+00","location":"עמק יזרעאל","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/06a432ee-864d-4aac-a60c-7eb7bd5cd691.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMDZhNDMyZWUtODY0ZC00YWFjLWE2MGMtN2ViN2JkNWNkNjkxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQ0OTY1MjEsImV4cCI6MjA5OTg1NjUyMX0.pRMko9e67KD_gsQrKDUUwHZ6jyZHpplGTbBI1pVsi98","external_link":"https://www.eventer.co.il/event/traktor_bateva/r91YL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"74486c73-2a21-4740-a09e-aa8620ce1eec","slug":"shlomi","title":"שלומי קוריאט","description":"שלומי קוריאט חוזר במופע סטנד אפ חדש שנון וחושפני שלא דופק חשבון לאף אחד ובעיקר מצחיק בטירוף. מביא לבמה את החוויה האישית שלו מחיי הנישואין, זוגיות, הורות וילדים, עם המון חן אישי, קצב ואנרגיה מטורפת.","region":"tzafon","kind":"show","event_date":"2026-08-01 18:30:00+00","location":"היכל התרבות מעלות תרשיחא","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/b5086338-97e0-4f21-b18c-97cbb63ac02c.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvYjUwODYzMzgtOTdlMC00ZjIxLWIxOGMtOTdjYmI2M2FjMDJjLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MDg5MDYsImV4cCI6MjA5ODk2ODkwNn0.XXkOzY16hxPVyI2m93rfi84RrHtMSSCvMHjdtVJKdGM","external_link":"https://castilia.co.il/he/Event/Order?eventId=5020","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"c6c79749-ec75-414a-9ab1-170707882466","slug":"rock-in-the-park","title":"רוק בפארק ","description":"פסטיבל רוק בפארק תחת כיפת השמיים! ניינטיז שואו מארחים ערב בלתי נשכח של הופעות וריקודים משנות ה-90. אסף אמדורסקי, ערן צור, יפעת נץ (המכשפות), אלי לולאי (להקת רוקפור) ומופע שנות ה-90. 5 הופעות ענק עם מסיבת ריקודים עד אור הבוקר!","region":"tzafon","kind":"party","event_date":"2026-08-06 18:00:00+00","location":"רמת השופט","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/8daa3680-92ba-4178-a942-17c2b4483d81.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvOGRhYTM2ODAtOTJiYS00MTc4LWE5NDItMTdjMmI0NDgzZDgxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM4NjUwMjQsImV4cCI6MjA5OTIyNTAyNH0.nLODrXTw9Corres6vB8OIBPAPMu4UQWdlY6qPm8HINw","external_link":"https://www.eventer.co.il/event/rock_park_2026/2Q1YL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"b7f55bb8-5731-482d-bce5-2a52ca4b7ad9","slug":"castilia","title":"תומר ישעיהו מארח את עמיר לב","description":"תומר ישעיהו - מופע להקה. אמפי עין הוד. ביום חמישי, 6 באוגוסט 2026 בשעה 21:00.","region":"tzafon","kind":"show","event_date":"2026-08-06 18:00:00+00","location":"אמפי עין הוד","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/e126cb26-9d58-46c2-8fe0-678e7bd2cd7d.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZTEyNmNiMjYtOWQ1OC00NmMyLThmZTAtNjc4ZTdiZDJjZDdkLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODU3ODEwNDUsImV4cCI6MjEwMTE0MTA0NX0.HCuARajRzpUbAFAkSNZMx_OPs64AY-X1pATsCcQaxRM","external_link":"https://castilia.co.il/he/Event/Order?eventId=5594","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"135d2d75-5791-4c84-b0e7-5809036f04de","slug":"ori-bruier","title":"אורי ברויר","description":"כוכב הטלוויזיה והרשת מציג סטנדאפ איכותי, שונה וקורע מצחוק! עם הפשטות וההומור העצמי, אורי סוחף את הקהל לפרצי צחוק בלתי נגמרים. אורי הוא סטנדאפיסט מיוחד ומבטיח הופעה מקורית ומצחיקה שלא תשכחו.","region":"tzafon","kind":"show","event_date":"2026-08-06 18:30:00+00","location":"היכל התרבות נהריה - חדש","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/a35ac263-1736-4ca7-8ff3-09cc9d3f903a.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvYTM1YWMyNjMtMTczNi00Y2E3LThmZjMtMDljYzlkM2Y5MDNhLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MDA0MTksImV4cCI6MjA5ODk2MDQxOX0.NShaCeyiHce5jlWC3G5_pFY0nvkEO1LD6pTc8QQ_Lt0","external_link":"https://castilia.co.il/he/Event/Order?eventId=5440","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"f354bbf1-ac5e-4f1e-8bb5-0dd3d66fe6ee","slug":"MIXIT COCKTAILS FESTIVAL","title":"MIXIT COCKTAILS FESTIVAL","description":"MIXIT COCKTAILS FESTIVAL - קוקטיילים ללא הגבלה במהלך כל האירוע! חוזרים להרים לכם את הקיץ עם פסטיבל קוקטיילים חופשי בקיסריה — חוויה של צהרי יום שישי, אוכל טעים, מוזיקה וקוקטיילים ללא הגבלה. 30+","region":"tzafon","kind":"party","event_date":"2026-08-07 09:00:00+00","location":"קיסריה","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/f527fdb2-b636-40e6-9ba7-ac4e9ee7f9ed.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZjUyN2ZkYjItYjYzNi00MGU2LTliYTctYWM0ZTllZTdmOWVkLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUxMzI2MzMsImV4cCI6MjEwMDQ5MjYzM30.f-eEEbJFj-KT65Ffub1c-idj1T26rgDgT49gp-v9Okc","external_link":"https://zygo.co.il/event/840773227869284822?tl=P6TS","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"30427e9b-4d8e-4684-b457-96d538577eed","slug":"luai-talpiut","title":"בגג של מלון לואי","description":"קבלת שבת כמו שאנחנו אוהבים. סידרנו לכם שישי לתפארת. פתיחת המסיבה בשעה 16:00. DJ סער משיח בסט פריסטייל. בר שתייה עם אלכוהול במחירים מוזלים ופיצות לנשנוש לאורך המסיבה.","region":"tzafon","kind":"party","event_date":"2026-08-07 13:00:00+00","location":"מלון לואי, רחוב החלוץ 35 חיפה","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/ac92915b-36ff-44a9-a1b7-efe84ef41f08.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvYWM5MjkxNWItMzZmZi00NGE5LWExYjctZWZlODRlZjQxZjA4LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUyMzgwMDMsImV4cCI6MjEwMDU5ODAwM30.jXFXwnisLpIxyedBmYffUxVhjGOM6nuyYqueYnioVmk","external_link":"https://eventbuzz.co.il/lp/event/lcqgz?s=19402","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"f6e277fb-1f1f-49f4-aee9-78712eb57cbc","slug":"gusbanka","title":"קיץ של נוסטלגיה בגושפנקא","description":"יש שירים שמספיק לשמוע את הצליל הראשון שלהם כדי לחזור לרגעים הכי יפים של החיים. בקיץ הזה אנחנו חוזרים לכל הלהיטים שעשו לנו את הילדות, הנעורים והלילות הכי גדולים – במסיבה אחת שכולה נוסטלגיה.","region":"tzafon","kind":"party","event_date":"2026-08-07 19:30:00+00","location":"גושפנקא","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/c60c6c72-df2b-4846-b748-cde9fa9475d9.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvYzYwYzZjNzItZGYyYi00ODQ2LWI3NDgtY2RlOWZhOTQ3NWQ5LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODU1MTQ5NDAsImV4cCI6MjEwMDg3NDk0MH0.-I5KVS5hkLjZfMHdCrh37y4uWrY83Q0JD2AJUBW1Hzg","external_link":"https://chillz.com/en/B5qd-3-7.8-B5qd?ref=18AHX","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"b8dc2683-48f9-4913-9708-a908b43625bc","slug":"Sound Garden","title":"Sound Garden","description":"Sound Garden אירוע שנולד מתוך כוונה אמיתית ליצור מרחב איכותי, מוקפד ועוצמתי למוזיקה. ליינאפ מדויק של 5 אמנים מהשורה הראשונה. מערכת סאונד ברמה הגבוהה ביותר, רחבה נעימה ומרווחת, בר במחירים חבריים, דוכני אוכל איכותיים.","region":"tzafon","kind":"party","event_date":"2026-08-07 20:30:00+00","location":"עמק יזרעאל","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/7789ade4-130b-4d9c-ba11-b5d7753be4a0.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNzc4OWFkZTQtMTMwYi00ZDljLWJhMTEtYjVkNzc1M2JlNGEwLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQzMDY4MTEsImV4cCI6MjA5OTY2NjgxMX0.baT8ruEX9fFftyiz3ZZiRumSkmlajzIpWJ5KnXdWeUI","external_link":"https://selector.org.il/e/PM8sGzILV7-","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"23278d1c-6e68-4b73-8ef2-eaa779ba5afd","slug":"urban music","title":"urban music","description":"Line Up: Shtubi, Space Cat, Bubble, Freak Show, Artifex, Squid, Larceuss. ציליה מטורפת, הגברה עוצמתית, טפטפות. גילאי 30+.","region":"merkaz","kind":"party","event_date":"2026-08-08 11:00:00+00","location":"ראשון לציון ","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/d0e3daf5-f59b-4a11-9908-c8f6d5a5c7c6.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZDBlM2RhZjUtZjU5Yi00YTExLTk5MDgtYzhmNmQ1YTVjN2M2LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUxNjcxNjYsImV4cCI6MjEwMDUyNzE2Nn0.nI9iZEVrhTYgHT_xaQ0Q5Gpfo2BRRmMC-nsSrOLR6OM","external_link":"https://zygo.co.il/event/830755245655339412/ZF10i08p9","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"821256fa-87f6-454c-a72d-53d16f0e8bf1","slug":"GROUNDZERO","title":"GROUNDZERO","description":"אנחנו מחזירים עטרה לישנה, חוזרים לגראונד זירו. חגיגה של טכנו באוויר הפתוח מול הכוכבים! אלקטרוני לקהלים בוגרים בלב הצפון, אלו שמבינים בדיוק איזה צלילים הם צריכים.","region":"tzafon","kind":"party","event_date":"2026-08-13 20:00:00+00","location":"תל עדשים","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/1b1ad4bc-4e65-44c9-a9ee-519491265242.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMWIxYWQ0YmMtNGU2NS00NGM5LWE5ZWUtNTE5NDkxMjY1MjQyLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQ0Njc5MzksImV4cCI6MjA5OTgyNzkzOX0.5n7WXB-PUiXbO42eApAEMGpS9p7L50P5AJTzrbhHAYY","external_link":"https://www.eventer.co.il/event/ground_zero_park/Lz1YL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"13661c48-9fa4-45f0-bb18-21e8088e0ed8","slug":"MOJO-SEXY-SUMMER","title":"MOJO SEXY SUMMER","description":"מסיבת המועדון הגדולה המטורפת והסקסית - בואו לוהטים עם בגדי רשת או בגדי ים וכל מה שיעשה לכם חם! הכניסה בלבוש שחור בלבד.","region":"tzafon","kind":"party","event_date":"2026-08-15 20:00:00+00","location":" יקותיאל בהרב 34, חיפה, ישראל","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/6184fcdf-270f-4e46-b3ea-02465531a131.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNjE4NGZjZGYtMjcwZi00ZTQ2LWIzZWEtMDI0NjU1MzFhMTMxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM1NDM4ODMsImV4cCI6MjA5ODkwMzg4M30.F4GD2d_M6hxLA--42kaXndijItOF30Ev68R-lJDAyGA","external_link":"https://selector.org.il/e/qnaZ6F_uwmH","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"87a10970-53ee-442d-affa-cc39435bf9da","slug":"maor edry","title":"חפלה בפארק ★ מאור אדרי בהופעה תחת כיפת השמיים","description":"מאור אדרי בהופעה חיה. גן אירועים כחול ירוק. מסיבה היסטורית באוויר הפתוח! מסיבה עם הופעה לתוך הלילה.","region":"tzafon","kind":"party","event_date":"2026-08-20 19:00:00+00","location":"תל עדשים","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/185070c1-3db6-48b8-b04a-34a6f2e42ea6.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMTg1MDcwYzEtM2RiNi00OGI4LWIwNGEtMzRhNmYyZTQyZWE2LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUzNTMyMDQsImV4cCI6MjEwMDcxMzIwNH0.en5vKRFoWVEuGHvYrLCS2jjZl_2s6WNJaGp7q5IJA8s","external_link":"https://www.eventer.co.il/event/maor_edri/JKWYL","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"f865f403-121f-4632-a4cc-563a1a402fd6","slug":"Ritual Festival","title":"Ritual Festival","description":"בלב המדבר הקסום, בין הרי הגרניט העתיקים לנופי בראשית עוצרי נשימה, יתקיים אחד מאירועי הטראנס המיוחדים והמרגשים של הקיץ. לילה אחד של חופש מוחלט, מוזיקה, טבע ואנשים יפים.","region":"darom","kind":"party","event_date":"2026-08-20 20:30:00+00","location":"אילת","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/268d286d-33da-4041-939a-a2a7d2d6a1f5.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMjY4ZDI4NmQtMzNkYS00MDQxLTkzOWEtYTJhN2QyZDZhMWY1LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM5NzM5NzEsImV4cCI6MjA5OTMzMzk3MX0.kuBe3vX8ot0DYan3FkhWl6as-44DGiFL-Jkcv7s2qyM","external_link":"https://zygo.co.il/event/150787125454398583/ZF10i08p9","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"92dd7c53-7bd9-4d3d-ac63-51d1cc3ef876","slug":"wain in offer","title":"פסטיבל היין בסמי עופר","description":"אצטדיון סמי עופר פותח את שעריו לפסטיבל היין הצפוני שמארח מגוון יקבים איכותיים ומובחרים המגישים יין חופשי לאורך כל האירוע. קוד לבוש - לבן בלבד. דוכני אמנים, קולינריה בתשלום.","region":"tzafon","kind":"party","event_date":"2026-08-21 08:00:00+00","location":"סמי עופר","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/dc630a39-877a-4d64-a049-5f6436660c1e.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZGM2MzBhMzktODc3YS00ZDY0LWEwNDktNWY2NDM2NjYwYzFlLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUxMzMwMjUsImV4cCI6MjEwMDQ5MzAyNX0.2kG1AFeGiRu9-_qsCKqUvo0aB7VXN843VISMBHYThSI","external_link":"https://go-out.co/event/1783843774426?ref=a39faaeagg","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"7dee20eb-370b-43d2-b6de-4e94c34ac9c7","slug":"daniel-cohen-kiriat-haim","title":"דניאל כהן בקרית חיים","description":"דניאל כהן, קומיקאי, נשוי לראש הכת ואבא גאה לסגן ראש הכת ולממלא מקום משנה לסגן ראש הכת. הסטנדאפיסט המוביל ותופעת הרשת במופע סטנדאפ משובח מושחז ובוגר שלא כדאי להחמיץ!","region":"tzafon","kind":"show","event_date":"2026-08-21 19:00:00+00","location":"בית נגלר - ק. חיים","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/d02d5701-d8ba-44fd-aa96-4a2f96a586b5.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZDAyZDU3MDEtZDhiYS00NGZkLWFhOTYtNGEyZjk2YTU4NmI1LmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MDk4NzMsImV4cCI6MjA5ODk2OTg3M30.M0XAfA7CyDklaz8ob81ApU0Fl2K24rYjhnNIKA68tEQ","external_link":"https://castilia.co.il/he/Event/Order?eventId=5479","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"1a22c43d-54d0-4018-9154-54fbbc0be48e","slug":"GAGARIN TEL AVIV","title":"GAGARIN TEL AVIV","description":"DECISION FESTIVAL — איפה שהמוזיקה, האנרגיה והאנשים הופכים לאחד. ב-27 באוגוסט אנחנו נפגשים בלב תל אביב במתחם הגגרין תל אביב. שלוש עולמות: המה הבמה המרכזית, NOVA ROOM, RED ROOM. MAIN STAGE: PETTRA, OMNYA (AFTERLIFE), DEJAVU, SELA-V, ISADORA, HAFI, ABALE, DANINO.","region":"merkaz","kind":"party","event_date":"2026-08-27 20:30:00+00","location":"קיבוץ גלויות 13 תל אביב ","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/642b20b8-93b0-4c47-9dd4-2ec43fcd4f12.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNjQyYjIwYjgtOTNiMC00YzQ3LTlkZDQtMmVjNDNmY2Q0ZjEyLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODU3ODA4NjMsImV4cCI6MjEwMTE0MDg2M30.GbiTyvVwDDEhcnjXMccD5qRdrDXdJhC7LNR_TZR2CpY","external_link":"https://zygo.co.il/event/590865022737830873/ZF10i08p9","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"c6fb99f6-3c59-4155-8961-3aeef7bda87e","slug":"AMNEZIA FESTIVAL EILAT","title":"אמנזיה אילת 2026","description":"AMNEZIA FESTIVAL EILAT אמנזיה אילת 2026","region":"darom","kind":"party","event_date":"2026-09-03 08:00:00+00","location":"אילת","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/e8169868-0b0c-4c17-90cf-bde233891881.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZTgxNjk4NjgtMGIwYy00YzE3LTkwY2YtYmRlMjMzODkxODgxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQ0Njc3NzEsImV4cCI6MjA5OTgyNzc3MX0.aAiE3eVlis3DpDJbwzFKnuFRTqnOi77OnohFoTmEQq0","external_link":"https://go-out.co/event/amneziaeilat?ref=a39faaeagg","price":null,"featured":false,"meta_title":null,"meta_description":null},
  {"id":"d4a68ef9-812a-4b2d-8ac6-ac0ffc758e7a","slug":"daniel","title":"דניאל סטיופין","description":"השחקן והקומיקאי דניאל סטיופין (אנטולי \"קופה ראשית\") מגיע לקדמת הבמה עם מופע סטנדאפ מיוחד, מרגש וקורע מצחוק. מסע של לילה אחד מטורף ששינה את חייו מקצה לקצה.","region":"tzafon","kind":"show","event_date":"2026-09-03 18:00:00+00","location":"היכל התרבות נהריה - חדש","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/570451a1-78c4-4dd3-88ab-b95a4db35dea.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvNTcwNDUxYTEtNzhjNC00ZGQzLTg4YWItYjk1YTRkYjM1ZGVhLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODM2MDg2OTMsImV4cCI6MjA5ODk2ODY5M30.y9R37qVn459JH-1b9vcq1HXkBvush6EP3qcNKbWCB8I","external_link":"https://castilia.co.il/he/Event/Order?eventId=5382","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"40e6ede6-8430-4d55-8bdf-1d0e3215da71","slug":"AMNEZIA ","title":"AMNEZIA - החווה של אמנזיה 2026","description":"חיכינו לרגע הזה. לרגע שבו המדבר קורא לנו לחזור הביתה. כשהאוויר של סוף האביב פוגש את החום המלטף של אילת, אנחנו חוזרים לחוות הגמלים כדי לכתוב את הפרק המרהיב ביותר בתולדות אמנזיה.","region":"darom","kind":"party","event_date":"2026-09-04 01:09:00+00","location":"אילת","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/fdfe8d1e-4168-4563-bc52-f619534e570f.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZmRmZThkMWUtNDE2OC00NTYzLWJjNTItZjYxOTUzNGU1NzBmLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQ2MzY1NTgsImV4cCI6MjA5OTk5NjU1OH0.a68hD6fdFFWBioIhr88jsaeS7Or_5ieJst0Ltsl05oQ","external_link":"https://go-out.co/event/1781624965367?ref=a39faaeagg","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"a9f1bc0a-9066-43c5-abb2-9bf441727d3c","slug":"dana-berger","title":"דנה ברגר","description":"דנה ברגר בהופעה חיה. אמפי עין הוד.","region":"tzafon","kind":"show","event_date":"2026-09-18 16:30:00+00","location":"אמפי עין הוד","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/81d2a51a-0f4c-4d25-aae2-fe831fa1747b.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvODFkMmE1MWEtMGY0Yy00ZDI1LWFhZTItZmU4MzFmYTE3NDdiLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUxNjY5NzQsImV4cCI6MjEwMDUyNjk3NH0.MfBjqCbKFUURNZQo8vJXDqEBFaLDjwrcbZb5Gnljqn8","external_link":"https://castilia.co.il/he/Event/Order?eventId=5668","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"8fd26f0a-3452-45e0-bb97-2e968b500b26","slug":"Ehud Banai","title":"אהוד בנאי עם הרכב ג'יש","description":"אהוד בנאי עם הרכב ג'יש – מופע של חברות, אמנות ומוזיקה. אמפי עין הוד.","region":"tzafon","kind":"show","event_date":"2026-09-29 16:30:00+00","location":"אמפי עין הוד","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/dda9a501-7cb7-4cc5-81fb-6d343ac90ee1.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvZGRhOWE1MDEtN2NiNy00Y2M1LTgxZmItNmQzNDNhYzkwZWUxLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODQyMDgwNjcsImV4cCI6MjA5OTU2ODA2N30.PQU7wmpYiQ33IJKsJ_CAHoAkND1L94iKJFM1TX_lsV8","external_link":"https://castilia.co.il/he/Event/Order?eventId=5655","price":null,"featured":true,"meta_title":null,"meta_description":null},
  {"id":"c0e8cac6-7b96-444c-8f79-95e2f05814bb","slug":"OMAYA CELEBRATING","title":"OMAYA CELEBRATING 1 YEAR","description":"חיכינו לרגע הזה, לרגע שבו המדבר קורא לנו לחזור הביתה. Sound Garden אירוע שנולד מתוך כוונה אמיתית ליצור מרחב איכותי, מוקפד ועוצמתי למוזיקה, לאנשים ולסטנדרט שאנחנו מאמינים שמגיע לקהילה שלנו. ליינאפ מדויק של 5 אמנים מהשורה הראשונה.","region":"darom","kind":"party","event_date":"2026-11-06 06:00:00+00","location":"ערבה","image_url":"https://cdysewodfwwobjeennns.supabase.co/storage/v1/object/sign/media/events/0e00dbcf-74c9-4850-8391-1e3b010b17ce.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV80YTkzYjI4My01OWRlLTQzOWQtYmUyZi0yYzgwOTcwMDY1YzAiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJtZWRpYS9ldmVudHMvMGUwMGRiY2YtNzRjOS00ODUwLTgzOTEtMWUzYjAxMGIxN2NlLmpwZyIsInNjb3BlIjoiZG93bmxvYWQiLCJpYXQiOjE3ODUxNjc0NzMsImV4cCI6MjEwMDUyNzQ3M30.ODze2Hlgb9kY9-JRi94MMHv0_yYIEDhru86s47ocqao","external_link":"https://selector.org.il/e/pcyad8bz_QU","price":null,"featured":true,"meta_title":null,"meta_description":null},
];

async function uniqueSlugFor(prisma: PrismaClient, title: string, excludeExternalId: string) {
  const base = slugify(title) || "event";
  let candidate = base;
  let suffix = 1;
  while (true) {
    const existing = await prisma.event.findUnique({ where: { slug: candidate } });
    if (!existing || existing.externalId === excludeExternalId) return candidate;
    suffix += 1;
    candidate = `${base}-${suffix}`;
  }
}

export async function syncPlusPartyEvents(prisma: PrismaClient) {
  const categoryIds = new Map<string, string>();
  for (const { slug, name, icon } of Object.values(KIND_CATEGORY)) {
    const category = await prisma.category.upsert({
      where: { slug },
      update: {},
      create: { slug, name, icon },
    });
    categoryIds.set(slug, category.id);
  }

  let created = 0;
  let updated = 0;

  for (const source of SOURCE_EVENTS) {
    const externalId = `${PLUSPARTY_SOURCE}:${source.id}`;
    const categorySlug = KIND_CATEGORY[source.kind].slug;
    const slug = await uniqueSlugFor(prisma, source.title, externalId);

    const data = {
      slug,
      title: source.title,
      description: source.description?.trim() || "פרטים נוספים בעמוד האירוע החיצוני.",
      coverImageUrl: source.image_url ?? "",
      startDate: new Date(source.event_date),
      venueName: source.location?.trim() || "יפורסם בקרוב",
      city: REGION_LABELS[source.region],
      priceLabel: source.price,
      affiliateUrl: source.external_link ?? "",
      affiliateNetwork: networkFromUrl(source.external_link),
      status: "PUBLISHED" as const,
      featured: source.featured,
      metaTitle: source.meta_title,
      metaDescription: source.meta_description,
      categoryId: categoryIds.get(categorySlug)!,
    };

    const existing = await prisma.event.findUnique({ where: { externalId } });
    if (existing) {
      await prisma.event.update({ where: { externalId }, data });
      updated += 1;
    } else {
      await prisma.event.create({ data: { ...data, externalId } });
      created += 1;
    }
  }

  return { created, updated, total: SOURCE_EVENTS.length };
}
